My pull request on News Reader App
alexvalentin/News-Reader pull request #1
Opened 2021-12-03 14:37 UTC by alexvalentin

2021-12-06 15:28 UTC, Misca requested changes
good job 👍  almost there

2021-12-06 15:28 UTC, Misca commented on app/build.gradle
> +    implementation "androidx.room:room-rxjava2:$room_version"
we shouldn't need room library in app, just in the data library as those responsabilities are better suited there

2021-12-06 15:28 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
Let's rename this activity class to something more meaningfull

2021-12-06 15:28 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/feature/newslist/adapter/RecyclerViewAdapter.java
> +public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.TaskViewHolder> {
RecyclerViewAdapter is named it could serve all recycler but it's not that general, let's rename this class to something more specific

2021-12-06 15:28 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/feature/newslist/listener/OnArticleSelected.java
> +    void onDeleteItemSelected(ArticleItemViewModel item);
we probably don't probably need to the onDeleteItemSelected, maybe we can give rid of it

2021-12-06 15:28 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/feature/newslist/model/ArticleItemViewModel.java
> +    public final String image;
final fields, nice!  👍

2021-12-06 15:28 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/feature/newslist/model/EventModel.java
> +    public enum EventType {
we don't need this event wrapper as we're not adding or editting news articles

2021-12-06 18:56 UTC, alexvalentin commented
I have updated the issues after the pull request and solved remote-tracking branch, some issues about an old layout and a class.

2021-12-07 08:20 UTC, Misca requested changes
one more round, getting closer 👍

2021-12-07 08:20 UTC, Misca commented on app/build.gradle
> +    //implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0'
let's cleanup commented lines, ne need for commented code, we got git for that

2021-12-07 08:20 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/BeginTransitionToFragmentActivity.java
> +public class BeginTransitionToFragmentActivity extends AppCompatActivity {
Let's name this activity oriented towards the feature, not to the implementation details, such as if we decide to change what we do inside such class, we should not need to change the name of the activity aswell. Let's keep it simple and less original. Maybe something like NewsActivity.

2021-12-07 08:20 UTC, Misca commented on app/src/main/java/com/alexandruvalentinconstantin/newsreader/feature/newslist/model/EventModel.java
> +public class EventModel {
this event wrapper seems useless at this point, let's remove and use the ArticleItemViewModel directly

2021-12-07 08:20 UTC, Misca commented on data/src/main/java/com/alexandruvalentinconstantin/data/NewsRepository.java
> +    Completable deleteItem(int itemId);
we could reduce this interface, exposing the repository for saveArticleItem and delete item, can bring less encapsulation, might allow the UI to break. Considering deleteItem and saveArticleItem are not needed, let's delete them

2021-12-07 08:20 UTC, Misca commented on data/src/main/java/com/alexandruvalentinconstantin/data/NewsRepository.java
> +    Single<List<Article>> getNewsArticles();
there seems to be a duplicated method for getting the Single<List<Article>>. Let's keep only one of these.

2021-12-08 09:06 UTC, Misca approved these changes
Good job, Alex! 👍

2021-12-08 09:21 UTC, merged